import { TODAY } from "../data/seed";
import type {
  CallOutcome,
  DueBill,
  ExecAudit,
  ExecAutomation,
  ExecMeeting,
  ExecReminderRule,
  ExecTask,
  SalesActivity,
} from "./types";

/** Deterministic date helper relative to the demo "today". */
export function day(offset: number): string {
  const d = new Date(`${TODAY}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + offset);
  return d.toISOString().slice(0, 10);
}

const salesOwners = ["u5", "u6", "u10", "u14"];
const financeOwners = ["u3", "u4"];

export const execTasks: ExecTask[] = [
  {
    id: "xt1",
    name: "Call Al Romansiah about Q4 renewal",
    department: "Sales",
    ownerId: "u5",
    requestedById: "u2",
    clientId: "c1",
    brand: "Al Romansiah",
    category: "Call",
    priority: "High",
    status: "In Progress",
    createdDate: day(-3),
    startDate: day(-1),
    dueDate: day(0),
    dueTime: "14:00",
    slaHours: 24,
    notes: "Confirm renewal scope before proposal is issued.",
    attachments: ["renewal-brief.pdf"],
    comments: [],
    nextAction: "Send renewal summary email",
    escalation: "None",
  },
  {
    id: "xt2",
    name: "Send revised quotation to Nana Direct",
    department: "Sales",
    ownerId: "u5",
    requestedById: "u5",
    clientId: "c2",
    category: "Proposal",
    priority: "Critical",
    status: "Assigned",
    createdDate: day(-2),
    startDate: day(-1),
    dueDate: day(0),
    dueTime: "17:00",
    slaHours: 24,
    notes: "Coverage recovery pricing agreed in Tuesday meeting.",
    attachments: [],
    comments: [],
    meetingId: "xm1",
    nextAction: "Issue quotation v3",
    escalation: "None",
    auto: true,
  },
  {
    id: "xt3",
    name: "Prepare client billing documents — Talabat Egypt",
    department: "Finance",
    ownerId: "u4",
    requestedById: "u3",
    clientId: "c3",
    category: "Invoice",
    priority: "Critical",
    status: "Waiting",
    createdDate: day(-9),
    startDate: day(-8),
    dueDate: day(-5),
    dueTime: "12:00",
    slaHours: 48,
    notes: "Waiting on signed delivery report from Operations.",
    attachments: [],
    comments: [],
    billId: "xb3",
    nextAction: "Chase delivery report",
    escalation: "Manager Escalated",
    blocked: true,
    auto: true,
  },
  {
    id: "xt4",
    name: "Client payment reminder — Talabat Egypt",
    department: "Finance",
    ownerId: "u4",
    requestedById: "u3",
    clientId: "c3",
    category: "Collection",
    priority: "Critical",
    status: "Assigned",
    createdDate: day(-6),
    startDate: day(-4),
    dueDate: day(-2),
    dueTime: "10:00",
    slaHours: 24,
    notes: "EGP 5.25M outstanding past 30 days.",
    attachments: [],
    comments: [],
    billId: "xb3",
    nextAction: "Escalate to CFO call",
    escalation: "Manager Escalated",
    auto: true,
  },
  {
    id: "xt5",
    name: "Confirm invoice sent — Cilantro Cafés",
    department: "Finance",
    ownerId: "u4",
    requestedById: "u3",
    clientId: "c4",
    category: "Invoice",
    priority: "Medium",
    status: "Completed",
    createdDate: day(-7),
    startDate: day(-6),
    dueDate: day(-4),
    dueTime: "16:00",
    completedDate: day(-4),
    slaHours: 24,
    notes: "Invoice INV-EG-2026-0209 emailed to AP desk.",
    attachments: [],
    comments: [],
    billId: "xb4",
    nextAction: "—",
    escalation: "None",
    auto: true,
  },
  {
    id: "xt6",
    name: "Meeting follow-up: Emaar winter brief",
    department: "Sales",
    ownerId: "u6",
    requestedById: "u2",
    clientId: "c5",
    category: "Meeting Action",
    priority: "High",
    status: "New",
    createdDate: day(0),
    startDate: day(0),
    dueDate: day(1),
    dueTime: "11:00",
    slaHours: 24,
    notes: "Client asked for two creator tiers and a media plan.",
    attachments: [],
    comments: [],
    meetingId: "xm2",
    nextAction: "Draft media plan",
    escalation: "None",
    auto: true,
  },
  {
    id: "xt7",
    name: "Contract renewal signature — Sultan Center",
    department: "Sales",
    ownerId: "u10",
    requestedById: "u9",
    clientId: "c6",
    category: "Contract",
    priority: "High",
    status: "In Review",
    createdDate: day(-5),
    startDate: day(-4),
    dueDate: day(2),
    dueTime: "13:00",
    slaHours: 72,
    notes: "Legal review complete, awaiting client counter-signature.",
    attachments: ["contract-v4.pdf"],
    comments: [],
    nextAction: "Chase signature",
    escalation: "None",
  },
  {
    id: "xt8",
    name: "Payment confirmation — Al Romansiah milestone 1",
    department: "Finance",
    ownerId: "u3",
    requestedById: "u2",
    clientId: "c1",
    category: "Payment Confirmation",
    priority: "Medium",
    status: "Completed",
    createdDate: day(-4),
    startDate: day(-3),
    dueDate: day(-2),
    dueTime: "15:00",
    completedDate: day(-2),
    slaHours: 24,
    notes: "SAR 228,000 received and matched.",
    attachments: [],
    comments: [],
    billId: "xb1",
    nextAction: "—",
    escalation: "None",
  },
  {
    id: "xt9",
    name: "Follow-up call — Cilantro Ramadan scoping",
    department: "Sales",
    ownerId: "u14",
    requestedById: "u7",
    clientId: "c4",
    category: "Follow-up",
    priority: "Medium",
    status: "Assigned",
    createdDate: day(-1),
    startDate: day(0),
    dueDate: day(0),
    dueTime: "16:30",
    slaHours: 8,
    notes: "Client requested indicative budget bands.",
    attachments: [],
    comments: [],
    nextAction: "Share budget bands",
    escalation: "None",
  },
  {
    id: "xt10",
    name: "Internal request: creator cost breakdown",
    department: "Finance",
    ownerId: "u3",
    requestedById: "u5",
    clientId: "c2",
    category: "Internal Request",
    priority: "Low",
    status: "In Progress",
    createdDate: day(-2),
    startDate: day(-1),
    dueDate: day(3),
    dueTime: "12:00",
    slaHours: 72,
    notes: "Needed for Nana Direct quotation.",
    attachments: [],
    comments: [],
    nextAction: "Send cost sheet",
    escalation: "None",
  },
  {
    id: "xt11",
    name: "Issue invoice — Nana Direct advance",
    department: "Finance",
    ownerId: "u4",
    requestedById: "u5",
    clientId: "c2",
    category: "Invoice",
    priority: "High",
    status: "Assigned",
    createdDate: day(-1),
    startDate: day(0),
    dueDate: day(1),
    dueTime: "12:00",
    slaHours: 24,
    notes: "50% advance per signed SOW.",
    attachments: [],
    comments: [],
    billId: "xb2",
    nextAction: "Create invoice in finance",
    escalation: "None",
    auto: true,
  },
  {
    id: "xt12",
    name: "Approval: Emaar discount above 12%",
    department: "Sales",
    ownerId: "u2",
    requestedById: "u6",
    clientId: "c5",
    category: "Approval",
    priority: "High",
    status: "In Review",
    createdDate: day(-1),
    startDate: day(-1),
    dueDate: day(0),
    dueTime: "18:00",
    slaHours: 24,
    notes: "Discount requires executive sign-off.",
    attachments: [],
    comments: [],
    nextAction: "Approve or reject",
    escalation: "None",
  },
  {
    id: "xt13",
    name: "Collection call — Sultan Center October balance",
    department: "Finance",
    ownerId: "u3",
    requestedById: "u9",
    clientId: "c6",
    category: "Collection",
    priority: "Medium",
    status: "Assigned",
    createdDate: day(-1),
    startDate: day(1),
    dueDate: day(4),
    dueTime: "11:00",
    slaHours: 48,
    notes: "KWD 12,400 due at month end.",
    attachments: [],
    comments: [],
    billId: "xb5",
    nextAction: "Schedule call",
    escalation: "None",
  },
  {
    id: "xt14",
    name: "Quotation follow-up — Emaar creator tiers",
    department: "Sales",
    ownerId: "u6",
    requestedById: "u6",
    clientId: "c5",
    category: "Proposal",
    priority: "Medium",
    status: "Waiting",
    createdDate: day(-6),
    startDate: day(-5),
    dueDate: day(-1),
    dueTime: "14:00",
    slaHours: 48,
    notes: "Client procurement has not replied.",
    attachments: [],
    comments: [],
    nextAction: "Second reminder email",
    escalation: "Notified",
  },
  {
    id: "xt15",
    name: "Confirm bank transfer — Cilantro milestone 1",
    department: "Finance",
    ownerId: "u4",
    requestedById: "u3",
    clientId: "c4",
    category: "Payment Confirmation",
    priority: "Medium",
    status: "Completed",
    createdDate: day(-10),
    startDate: day(-9),
    dueDate: day(-8),
    dueTime: "12:00",
    completedDate: day(-9),
    slaHours: 24,
    notes: "EGP 3.1M cleared.",
    attachments: [],
    comments: [],
    nextAction: "—",
    escalation: "None",
  },
  {
    id: "xt16",
    name: "Prepare collection forecast pack",
    department: "Finance",
    ownerId: "u3",
    requestedById: "u2",
    category: "Internal Request",
    priority: "High",
    status: "In Progress",
    createdDate: day(-2),
    startDate: day(-1),
    dueDate: day(1),
    dueTime: "09:00",
    slaHours: 48,
    notes: "Weekly expected collections for management review.",
    attachments: [],
    comments: [],
    nextAction: "Finish September view",
    escalation: "None",
  },
  {
    id: "xt17",
    name: "Client commitment: send campaign recap deck",
    department: "Sales",
    ownerId: "u14",
    requestedById: "u14",
    clientId: "c3",
    category: "Meeting Action",
    priority: "Critical",
    status: "Assigned",
    createdDate: day(-8),
    startDate: day(-7),
    dueDate: day(-6),
    dueTime: "17:00",
    slaHours: 24,
    notes: "Promised in the escalation meeting with the CMO.",
    attachments: [],
    comments: [],
    meetingId: "xm3",
    nextAction: "Build recap deck",
    escalation: "Executive Escalated",
    auto: true,
  },
  {
    id: "xt18",
    name: "Weekly overdue review with Sales Manager",
    department: "Sales",
    ownerId: "u5",
    requestedById: "u2",
    category: "Internal Request",
    priority: "Medium",
    status: "New",
    createdDate: day(0),
    startDate: day(1),
    dueDate: day(2),
    dueTime: "10:00",
    slaHours: 48,
    notes: "Review all overdue client actions.",
    attachments: [],
    comments: [],
    nextAction: "Prepare list",
    escalation: "None",
  },
  {
    id: "xt19",
    name: "Payment due today — Al Romansiah milestone 2",
    department: "Finance",
    ownerId: "u3",
    requestedById: "u3",
    clientId: "c1",
    category: "Collection",
    priority: "High",
    status: "Assigned",
    createdDate: day(-5),
    startDate: day(0),
    dueDate: day(0),
    dueTime: "12:00",
    slaHours: 8,
    notes: "SAR 92,000 balance outstanding.",
    attachments: [],
    comments: [],
    billId: "xb1",
    nextAction: "Call AP contact",
    escalation: "None",
    auto: true,
  },
  {
    id: "xt20",
    name: "Draft proposal — Talabat recovery retainer",
    department: "Sales",
    ownerId: "u14",
    requestedById: "u7",
    clientId: "c3",
    category: "Proposal",
    priority: "High",
    status: "In Progress",
    createdDate: day(-3),
    startDate: day(-2),
    dueDate: day(3),
    dueTime: "15:00",
    slaHours: 72,
    notes: "Six-month recovery retainer with monthly reporting.",
    attachments: [],
    comments: [],
    nextAction: "Finish pricing model",
    escalation: "None",
  },
];

export const execMeetings: ExecMeeting[] = [
  {
    id: "xm1",
    clientId: "c2",
    title: "Nana Direct — coverage recovery",
    purpose: "Agree recovery plan and revised pricing",
    ownerId: "u5",
    attendees: ["u5", "u3"],
    date: day(-2),
    time: "11:00",
    notes:
      "Client unhappy with August posting coverage. Agreed compensation posts and revised Q4 pricing.",
    outcome: "Revised quotation to be sent with two compensation waves.",
    clientRequests: ["Compensation posts in September", "Revised Q4 pricing"],
    commitments: [
      {
        id: "xc1",
        text: "Send revised quotation",
        ownerId: "u5",
        dueDate: day(0),
        converted: true,
      },
      {
        id: "xc2",
        text: "Share creator cost breakdown",
        ownerId: "u3",
        dueDate: day(3),
        converted: true,
      },
    ],
    nextAction: "Quotation review call",
    followUpDate: day(4),
    attachments: ["coverage-report.pdf"],
    status: "Completed",
  },
  {
    id: "xm2",
    clientId: "c5",
    title: "Emaar Hospitality — winter season brief",
    purpose: "Scope winter campaign",
    ownerId: "u6",
    attendees: ["u6", "u2"],
    date: day(0),
    time: "09:30",
    notes: "Winter season across three properties.",
    outcome: "Client wants two creator tiers plus a media plan by end of week.",
    clientRequests: ["Two creator tiers", "Media plan"],
    commitments: [
      {
        id: "xc3",
        text: "Draft media plan and tiers",
        ownerId: "u6",
        dueDate: day(1),
        converted: true,
      },
    ],
    nextAction: "Present media plan",
    followUpDate: day(5),
    attachments: [],
    status: "Completed",
  },
  {
    id: "xm3",
    clientId: "c3",
    title: "Talabat Egypt — escalation with CMO",
    purpose: "Recover the relationship",
    ownerId: "u14",
    attendees: ["u14", "u7", "u2"],
    date: day(-7),
    time: "13:00",
    notes: "CMO raised delivery and reporting concerns.",
    outcome: "Recap deck and recovery retainer proposal promised.",
    clientRequests: ["Campaign recap deck", "Recovery plan"],
    commitments: [
      {
        id: "xc4",
        text: "Send campaign recap deck",
        ownerId: "u14",
        dueDate: day(-6),
        converted: true,
      },
      {
        id: "xc5",
        text: "Draft recovery retainer proposal",
        ownerId: "u14",
        dueDate: day(3),
        converted: true,
      },
    ],
    nextAction: "Present recovery retainer",
    followUpDate: day(3),
    attachments: [],
    status: "Pending Follow-up",
  },
  {
    id: "xm4",
    clientId: "c1",
    title: "Al Romansiah — Q4 renewal",
    purpose: "Renewal terms",
    ownerId: "u5",
    attendees: ["u5", "u2"],
    date: day(2),
    time: "10:00",
    notes: "",
    outcome: "",
    clientRequests: [],
    commitments: [],
    nextAction: "Prepare renewal pack",
    attachments: [],
    status: "Scheduled",
  },
  {
    id: "xm5",
    clientId: "c6",
    title: "Sultan Center — October targets",
    purpose: "Confirm targets and billing schedule",
    ownerId: "u10",
    attendees: ["u10", "u3"],
    date: day(3),
    time: "12:00",
    notes: "",
    outcome: "",
    clientRequests: [],
    commitments: [],
    nextAction: "Send agenda",
    attachments: [],
    status: "Scheduled",
  },
  {
    id: "xm6",
    clientId: "c4",
    title: "Cilantro — Ramadan 2027 scoping",
    purpose: "Early scoping",
    ownerId: "u14",
    attendees: ["u14"],
    date: day(-1),
    time: "15:00",
    notes: "Discussed indicative budget bands.",
    outcome: "Client asked for budget bands and a creator shortlist.",
    clientRequests: ["Budget bands", "Creator shortlist"],
    commitments: [
      {
        id: "xc6",
        text: "Share indicative budget bands",
        ownerId: "u14",
        dueDate: day(0),
        converted: true,
      },
    ],
    nextAction: "Budget bands follow-up",
    followUpDate: day(6),
    attachments: [],
    status: "Pending Follow-up",
  },
];

export const dueBills: DueBill[] = [
  {
    id: "xb1",
    clientId: "c1",
    invoiceNumber: "INV-SA-2026-0418",
    amount: 152000,
    paid: 60000,
    currency: "SAR",
    entityId: "sa",
    responsibleId: "u3",
    issueDate: day(-3),
    dueDate: day(0),
    status: "Due Today",
    lastFollowUp: day(-1),
    nextAction: "Call AP contact",
  },
  {
    id: "xb2",
    clientId: "c2",
    invoiceNumber: "INV-SA-2026-0421",
    amount: 310000,
    paid: 0,
    currency: "SAR",
    entityId: "sa",
    responsibleId: "u4",
    issueDate: day(-2),
    dueDate: day(4),
    status: "Due Soon",
    lastFollowUp: day(-2),
    nextAction: "Confirm invoice receipt",
  },
  {
    id: "xb3",
    clientId: "c3",
    invoiceNumber: "INV-EG-2026-0188",
    amount: 7250000,
    paid: 2000000,
    currency: "EGP",
    entityId: "eg",
    responsibleId: "u4",
    issueDate: day(-61),
    dueDate: day(-31),
    status: "Escalated",
    lastFollowUp: day(-4),
    nextAction: "CFO escalation call",
  },
  {
    id: "xb4",
    clientId: "c4",
    invoiceNumber: "INV-EG-2026-0203",
    amount: 3100000,
    paid: 3100000,
    currency: "EGP",
    entityId: "eg",
    responsibleId: "u4",
    issueDate: day(-9),
    dueDate: day(21),
    status: "Paid",
    lastFollowUp: day(-8),
    nextAction: "—",
  },
  {
    id: "xb5",
    clientId: "c6",
    invoiceNumber: "INV-KW-2026-0044",
    amount: 12400,
    paid: 0,
    currency: "KWD",
    entityId: "kw",
    responsibleId: "u3",
    issueDate: day(-6),
    dueDate: day(9),
    status: "Upcoming",
    lastFollowUp: day(-3),
    nextAction: "Pre-due reminder",
  },
  {
    id: "xb6",
    clientId: "c5",
    invoiceNumber: "INV-AE-2026-0131",
    amount: 186000,
    paid: 90000,
    currency: "AED",
    entityId: "ae",
    responsibleId: "u3",
    issueDate: day(-20),
    dueDate: day(-6),
    status: "Overdue",
    lastFollowUp: day(-2),
    nextAction: "Second reminder",
  },
  {
    id: "xb7",
    clientId: "c4",
    invoiceNumber: "INV-EG-2026-0209",
    amount: 3100000,
    paid: 0,
    currency: "EGP",
    entityId: "eg",
    responsibleId: "u4",
    issueDate: day(0),
    dueDate: day(30),
    status: "Preparing",
    lastFollowUp: "—",
    nextAction: "Prepare billing documents",
  },
  {
    id: "xb8",
    clientId: "c1",
    invoiceNumber: "INV-SA-2026-0430",
    amount: 96000,
    paid: 0,
    currency: "SAR",
    entityId: "sa",
    responsibleId: "u3",
    issueDate: day(-1),
    dueDate: day(1),
    status: "Due Soon",
    lastFollowUp: day(-1),
    nextAction: "Confirm approval",
  },
  {
    id: "xb9",
    clientId: "c2",
    invoiceNumber: "INV-SA-2026-0433",
    amount: 74000,
    paid: 0,
    currency: "SAR",
    entityId: "sa",
    responsibleId: "u4",
    issueDate: day(-1),
    dueDate: day(13),
    status: "Pending Approval",
    lastFollowUp: "—",
    nextAction: "Finance manager approval",
  },
  {
    id: "xb10",
    clientId: "c3",
    invoiceNumber: "INV-EG-2026-0215",
    amount: 1450000,
    paid: 500000,
    currency: "EGP",
    entityId: "eg",
    responsibleId: "u4",
    issueDate: day(-14),
    dueDate: day(-2),
    status: "Partially Paid",
    lastFollowUp: day(-1),
    nextAction: "Collect remaining balance",
  },
];

function activity(
  id: string,
  ownerId: string,
  clientId: string,
  offset: number,
  type: SalesActivity["type"],
  outcome: CallOutcome | undefined,
  note: string,
): SalesActivity {
  const base: SalesActivity = { id, ownerId, clientId, date: day(offset), type, note };
  return outcome ? { ...base, outcome } : base;
}

export const salesActivities: SalesActivity[] = (() => {
  const rows: SalesActivity[] = [];
  const clients = ["c1", "c2", "c3", "c4", "c5", "c6"];
  const outcomes: CallOutcome[] = ["Answered", "No Answer", "Follow-up Required"];
  let n = 0;
  for (let d = 0; d < 90; d += 1) {
    for (let i = 0; i < salesOwners.length; i += 1) {
      const seedN = (d * 7 + i * 13) % 11;
      if (seedN > 6) continue;
      n += 1;
      const owner = salesOwners[i]!;
      const client = clients[(d + i) % clients.length]!;
      const type: SalesActivity["type"] =
        seedN < 3
          ? "Call"
          : seedN === 3
            ? "Meeting Scheduled"
            : seedN === 4
              ? "Meeting Completed"
              : seedN === 5
                ? "Quotation Requested"
                : "Quotation Sent";
      rows.push(
        activity(
          `xa${n}`,
          owner,
          client,
          -d,
          type,
          type === "Call" ? outcomes[seedN % 3] : undefined,
          type === "Call" ? "Client call logged" : `${type} logged`,
        ),
      );
    }
  }
  return rows;
})();

export const execReminderRules: ExecReminderRule[] = [
  {
    id: "xr1",
    name: "5 days before bill due date",
    offset: "-5 days",
    channels: ["In-app", "Email"],
    repeatWhileOverdue: false,
    notifyManager: false,
    enabled: true,
  },
  {
    id: "xr2",
    name: "1 day before task due date",
    offset: "-1 day",
    channels: ["In-app", "Dashboard"],
    repeatWhileOverdue: false,
    notifyManager: false,
    enabled: true,
  },
  {
    id: "xr3",
    name: "Same day at 08:00",
    offset: "0 days",
    channels: ["In-app", "Email", "Dashboard"],
    repeatWhileOverdue: false,
    notifyManager: false,
    enabled: true,
  },
  {
    id: "xr4",
    name: "4 hours before due time",
    offset: "-4 hours",
    channels: ["In-app"],
    repeatWhileOverdue: false,
    notifyManager: false,
    enabled: true,
  },
  {
    id: "xr5",
    name: "Daily while overdue",
    offset: "+1 day",
    channels: ["In-app", "Email"],
    repeatWhileOverdue: true,
    notifyManager: true,
    enabled: true,
  },
];

export const execAutomations: ExecAutomation[] = [
  {
    id: "xn1",
    name: "Bill reminder ladder",
    when: "Bill due date is approaching",
    ifCriteria: "Status is not Paid",
    then: "Create Finance tasks at −5, −3, −1 and due day, notify owner and send email",
    enabled: true,
    runs: 184,
    lastRun: day(0),
  },
  {
    id: "xn2",
    name: "Meeting outcome to task",
    when: "Meeting outcome contains a commitment",
    ifCriteria: "Commitment has an owner and a date",
    then: "Create task with source = Client Meeting",
    enabled: true,
    runs: 63,
    lastRun: day(0),
  },
  {
    id: "xn3",
    name: "24-hour overdue escalation",
    when: "Task becomes overdue by 24 hours",
    ifCriteria: "Status is not Completed",
    then: "Notify employee and their manager",
    enabled: true,
    runs: 47,
    lastRun: day(-1),
  },
  {
    id: "xn4",
    name: "Critical overdue executive alert",
    when: "Task overdue by 5 days",
    ifCriteria: "Priority is High or Critical",
    then: "Escalate to Executive Management",
    enabled: true,
    runs: 11,
    lastRun: day(-2),
  },
  {
    id: "xn5",
    name: "Morning brief 08:00",
    when: "Every working day at 08:00",
    ifCriteria: "Employee has tasks, meetings or bills today",
    then: "Send personal morning brief",
    enabled: true,
    runs: 240,
    lastRun: day(0),
  },
  {
    id: "xn6",
    name: "End-of-day report 18:00",
    when: "Every working day at 18:00",
    ifCriteria: "Always",
    then: "Send employee summary and consolidated manager report",
    enabled: true,
    runs: 239,
    lastRun: day(-1),
  },
];

export const execAudit: ExecAudit[] = [
  {
    id: "xg1",
    at: `${day(0)} 08:00`,
    actorId: "u1",
    action: "Reminder sent",
    entity: "Bill",
    entityId: "xb1",
    detail: "Same-day reminder to Mostafa Kamel",
  },
  {
    id: "xg2",
    at: `${day(0)} 07:45`,
    actorId: "u1",
    action: "Task created",
    entity: "Task",
    entityId: "xt19",
    detail: "Auto-created from bill reminder ladder",
  },
  {
    id: "xg3",
    at: `${day(-1)} 18:02`,
    actorId: "u1",
    action: "Escalation triggered",
    entity: "Task",
    entityId: "xt17",
    detail: "Overdue 5 days — executive escalation",
  },
  {
    id: "xg4",
    at: `${day(-1)} 15:20`,
    actorId: "u14",
    action: "Meeting updated",
    entity: "Meeting",
    entityId: "xm6",
    detail: "Outcome recorded and 1 commitment converted",
  },
  {
    id: "xg5",
    at: `${day(-2)} 11:40`,
    actorId: "u5",
    action: "Owner changed",
    entity: "Task",
    entityId: "xt10",
    detail: "Reassigned to Mostafa Kamel",
  },
];

export const financeOwnerIds = financeOwners;
export const salesOwnerIds = salesOwners;
